Structure
front-end-by-rimantas/17-grupe-portfolio-personal pull request #7
Opened 2020-07-28 10:21 UTC by Deivis151

2020-07-28 10:35 UTC, Saulius20 submitted a review, later dismissed

2020-07-28 13:39 UTC, belauzas requested changes
Nereikėjo ištrinti reser.css turinio

2020-07-30 07:07 UTC, Generasu submitted a review, later dismissed

2020-07-30 07:33 UTC, Generasu submitted a review, later dismissed

2020-07-30 13:20 UTC, closed without merging